src/client/GL.NovoExtrato.Site/Models/ContaCorrenteListaModel.cs
using System.Collections.Generic;
using System.Linq;

namespace GL.NovoExtrato.Site.Models
{
    public class ContaCorrenteListaModel
    {
        public ContaCorrenteListaModel(IEnumerable<ContaCorrenteModel> contasCorrentes)
        {
            ContasCorrentes = contasCorrentes;
        }
        public IEnumerable<ContaCorrenteModel> ContasCorrentes { get; set; }
        public bool TemContaCorrente
        {
            get
            {
                return ContasCorrentes != null && ContasCorrentes.Any();
            }
        }
    }
}

src/client/GL.NovoExtrato.Site/Models/ContaCorrenteModel.cs
namespace GL.NovoExtrato.Site.Models
{
    public class ContaCorrenteModel
    {
        public int ClienteId { get; set; }
        public string ClienteNome { get; set; }
        public string NumeroDaConta { get; set; }
        public decimal SaldoEmConta { get; set; }
    }
}

src/client/GL.NovoExtrato.Site/Models/CriarClienteModel.cs
using System;
namespace GL.NovoExtrato.Site.Models
{
    public class CriarClienteModel
    {
        public CriarClienteModel()
        {
        }
    }
}

src/client/GL.NovoExtrato.Site/Models/CriarClientesModel.cs
using System.ComponentModel.DataAnnotations;
namespace GL.NovoExtrato.Site.Models
{
    public class CriarClientesModel
    {
        [Required(ErrorMessage ="Informe a quantidade de clientes")]
        public int Quantidade { get; set; }
    }
}

src/client/GL.NovoExtrato.Site/Models/CriarLancamentoModel.cs
using System.ComponentModel.DataAnnotations;

namespace GL.NovoExtrato.Site.Models
{
    public class CriarLancamentoModel
    {
        [Required(ErrorMessage = "Conta origem é obrigatório")]
        public string NumeroContaOrigem { get; set; }
        [Required(ErrorMessage = "Conta destino é obrigatório")]
        public string NumeroContaDestino { get; set; }
        [Required(ErrorMessage = "Tipo do lançamento é obrigatório")]
        public int Tipo { get; set; }
        [Required(ErrorMessage = "Valor é obrigatório")]
        [Range(1, int.MaxValue, ErrorMessage = "O valor de transferência deve ser maior que 0")]
        public decimal Valor { get; set; }
    }
}

src/client/GL.NovoExtrato.Site/Models/ErrorViewModel.cs
namespace GL.NovoExtrato.Site.Models
{
    public class ErrorViewModel
    {
        public ErrorViewModel()
        {
            Titulo = "Ocorreu um erro";
            Subtitulo = "Ocorreu um erro";
            Mensagem = "Ocorreu um erro";
        }
        public string Titulo { get; set; }
        public string Subtitulo { get; set; }
        public string Mensagem { get; set; }
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void Error500()
        {
            Titulo = "Ocorreu um erro interno";
            Subtitulo = "O serviço chamado está indisponível no momento.";
            Mensagem = "Não foi possível estabelecer conexão com o serviço solicitado, tente novamente.";
        }
    }
}

src/client/GL.NovoExtrato.Site/Models/ExtratoListaModel.cs
using System;
using System.Collections.Generic;

namespace GL.NovoExtrato.Site.Models
{
    public class ExtratoListaModel
    {
        public ExtratoListaModel(IEnumerable<ExtratoModel> extratos)
        {
            Extratos = extratos;
        }

        public IEnumerable<ExtratoModel> Extratos { get; set; }
    }
}

src/client/GL.NovoExtrato.Site/Models/ExtratoModel.cs
using System;
namespace GL.NovoExtrato.Site.Models
{
    public class ExtratoModel
    {
        public int ClienteId { get; set; }
        public DateTime CriadoEm { get; set; }
        public int Tipo { get; set; }
        public string TipoDescricao
        {
            get
            {
                if (Tipo == 1)
                    return "Transferência";
                else if (Tipo == 2)
                    return "TED";
                else if (Tipo == 4)
                    return "DOC";
                else if (Tipo == 8)
                    return "Depósito";
                return "Desconhecido";
            }
        }
        public decimal ValorTransacao { get; set; }
        public string Descricao { get; set; }
        public string ContaOrigem { get; set; }
        public string NomeClienteOrigem { get; set; }
        public string ContaDestino { get; set; }
        public string NomeClienteDestino { get; set; }
        public decimal Saldo { get; set; }
        public int TransacaoTipo { get; set; }
        public string TransacaoTipoDescricao
        {
            get
            {
                if (TransacaoTipo == 1)
                    return "Credito";
                else if (TransacaoTipo == 2)
                    return "Debito";
                else
                    return "Desconhecido";
            }
        }
    }
}

src/client/GL.NovoExtrato.Site/Controllers/ConsultaController.cs
using System.Linq;
using System.Threading.Tasks;
using GL.NovoExtrato.Site.Models;
using GL.NovoExtrato.Site.Services;
using Microsoft.AspNetCore.Mvc;
namespace GL.NovoExtrato.Site.Controllers
{
    public class ConsultaController : Controller
    {
        private readonly IConsultaServicoApi _serviceApi;

        public ConsultaController(IConsultaServicoApi serviceApi)
        {
            _serviceApi = serviceApi;
        }

        public async Task<IActionResult> Extrato(int id)
        {
            var extratos = await _serviceApi.ObterAsync(id);
            if (extratos != null)
                extratos = extratos.OrderByDescending(p => p.CriadoEm);
            var model = new ExtratoListaModel(extratos);
            return View(model);
        }
    }
}

src/client/GL.NovoExtrato.Site/Controllers/ContaCorrenteController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using GL.NovoExtrato.Site.Models;
using GL.NovoExtrato.Site.Services;
using Microsoft.AspNetCore.Mvc;
namespace GL.NovoExtrato.Site.Controllers
{
    public class ContaCorrenteController : Controller
    {
        private readonly IContaCorrenteServicoApi _serviceApi;

        public ContaCorrenteController(IContaCorrenteServicoApi serviceApi)
        {
            _serviceApi = serviceApi;
        }

        public async Task<IActionResult> Index()
        {
            var contas = await _serviceApi.ObterContas();
            var model = new ContaCorrenteListaModel(contas);
            return View(model);
        }

        public IActionResult CriarClientes()
        {
            return View(new CriarClientesModel());
        }

        [HttpPost]
        public async Task<IActionResult> CriarClientes(CriarClientesModel model)
        {
            if (ModelState.IsValid)
            {
                for (var i = 0; i < model.Quantidade; i++)
                {
                    await _serviceApi.CriarClienteAsync();
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult CriarLancamento()
        {
            return View(new CriarLancamentoModel());
        }

        [HttpPost]
        public async Task<IActionResult> CriarLancamento(CriarLancamentoModel model)
        {
            if (ModelState.IsValid)
            {
                await _serviceApi.CriarLancamento(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var error = new ErrorViewModel()
            {
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };

            if (HttpContext.Response.StatusCode == 500)
            {
                error.Error500();
            }
            return View(error);
        }
    }
}

src/client/GL.NovoExtrato.Site/Views/Consulta/Extrato.cshtml
@model GL.NovoExtrato.Site.Models.ExtratoListaModel
@{
    ViewData["Title"] = "Extrato inicial";
}

<h3>Extrato da conta</h3>
 <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Data</th>
              <th scope="col">Tipo</th>
              <th scope="col">Transação</th>
              <th scope="col">Valor</th>
              <th scope="col">Descrição</th>
              <th scope="col">Conta Origem</th>
              <th scope="col">Conta Destino</th>
              <th scope="col">Saldo</th>
            </tr>
          </thead>
          <tbody>
              @foreach (var extrato in Model.Extratos)
              {
                <tr>
                  <td>@extrato.CriadoEm</td>
                  <td>@extrato.TipoDescricao</td>
                  <td>@extrato.TransacaoTipoDescricao</td>
                  <td>@extrato.ValorTransacao</td>
                  <td>@extrato.Descricao</td>
                  <td>@extrato.ContaOrigem</td>
                  <td>@extrato.ContaDestino</td>
                  <td>@extrato.Saldo</td>
                </tr>
              }
          </tbody>
        </table>

src/client/GL.NovoExtrato.Site/Views/ContaCorrente/CriarClientes.cshtml
@model GL.NovoExtrato.Site.Models.CriarClientesModel
<form asp-action="criarclientes" method="post">
    <div class="text-center">
        <h3 class="display-4">Criar clientes</h3>
        <p>Informe abaixo a quantidade de clientes que deseja criar.</p>
    </div>
    <br/>
    <div class="row">
        <div class="col-4 mx-auto">
            <div class="form-group">
                <input type="text" class="form-control text-center" placeholder="Quantidade" asp-for="@Model.Quantidade">
                <span asp-validation-for="@Model.Quantidade" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-4 mx-auto">
            <div class="form-group">
                <button type="submit" class="btn btn-primary col-12"> Iniciar</button>
            </div>
        </div>
    </div>
</form>

src/client/GL.NovoExtrato.Site/Views/ContaCorrente/CriarLancamento.cshtml
@model GL.NovoExtrato.Site.Models.CriarLancamentoModel
@{
    ViewData["Title"] = "Novo lançamentosss";
}
<form asp-action="criarlancamento" method="post">
    <div class="container">
         <div class="text-center">
            <h3 class="display-4">Criar novo lançamento entre contas</h3>
            <p>Informe abaixo a quantidade de clientes que deseja criar.</p>
        </div>
        <br />
        <div class="row">
            <div class="col-4 mx-auto">
                <div class="form-group">
                    <label for="contaOrigem">Conta origem</label>
                    <input type="text" class="form-control" style="text-transform:uppercase;" id="contaOrigem" asp-for="@Model.NumeroContaOrigem" placeholder="Conta origem"/>
                    <span asp-validation-for="@Model.NumeroContaOrigem" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-4 mx-auto">
                <div class="form-group">
                    <label for="contaDestino">Conta Destino</label>
                    <input type="text" class="form-control" style="text-transform:uppercase;" id="contaDestino" asp-for="@Model.NumeroContaDestino" placeholder="Conta destino"/>
                    <span asp-validation-for="@Model.NumeroContaDestino" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-4 mx-auto">
                <div class="form-group">
                    <label for="tipo">Tipo de lançamento</label>
                    <select class="form-control" asp-for="@Model.Tipo">
                        <option value="1">Transferência</option>
                        <option value="2">TED</option>
                        <option value="4">DOC</option>
                    </select>
                    <span asp-validation-for="@Model.Tipo" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-4 mx-auto">
                <div class="form-group">
                    <label for="contaOrigem">Valor</label>
                    <input type="text" class="form-control" id="valor" asp-for="@Model.Valor" placeholder="Valor"/>
                    <span asp-validation-for="@Model.Valor" class="text-danger"></span>
                </div>
            </div>
        </div>
         <div class="row">
             <div class="col-4 mx-auto">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary col-12"> Salvar</button>
                </div>
            </div>
        </div>
    </div>
</form>

src/client/GL.NovoExtrato.Site/Views/ContaCorrente/Index.cshtml
@model GL.NovoExtrato.Site.Models.ContaCorrenteListaModel
@{
    ViewData["Title"] = "Página inicial";
}
    @if (Model.TemContaCorrente)
    {
        <div class="row">
            <div class="col-12">
                <a class="btn btn-success" asp-action="criarclientes">Novos clientes</a>
                <a class="btn btn-success" asp-action="criarlancamento">Novo lançamento</a>
            </div>
        </div>
        <br/>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Cliente</th>
              <th scope="col">Conta</th>
              <th scope="col">Saldo</th>
              <th scope="col">Extrato</th>
            </tr>
          </thead>
          <tbody>
              @foreach (var conta in Model.ContasCorrentes)
              {
                <tr>
                  <td>@conta.ClienteNome</td>
                  <td>@conta.NumeroDaConta</td>
                  <td>@conta.SaldoEmConta</td>
                  <td><a class="btn-sm btn-primary" asp-action="extrato" asp-controller="consulta" asp-route-id="@conta.ClienteId">Ver extrato</a></td>
                </tr>
              }
          </tbody>
        </table>
    }
    else
    {
       <div class="text-center">
            <h1 class="display-4">Bem-vindo ao Novo Extrato</h1>
            <p>Clique <a asp-controller="contacorrente" asp-action="criarclientes">aqui</a> para criar os clientes e iniciar os testes.</p>
        </div>
    }

src/client/GL.NovoExtrato.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Novo extrato</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="ContaCorrente" asp-action="Index">Novo Extrato</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Novo Extrato
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>